CREATE OR REPLACE TRIGGER
LogTransaction
AFTER INSERT
ON Transactions

FOR EACH ROW
BEGIN
    INSERT INTO AuditLog(TransactionID,ActionDate,ActionType)
    VALUES(:NEW.TransactionID, SYSDATE, 'NEW TRANSACTION' );
END;
/


--Table to store Audit records whenever user tries to insert values on Transaction Table
--it keeps copy of the all records which is being inserted on transaction

CREATE TABLE AuditLog (
    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransactionID NUMBER,
    ActionDate DATE,
    ActionType VARCHAR2(50));